"""delete column deportamet:str in table Users

Revision ID: 23f3a5ee5cd3
Revises: 47458769c1af
Create Date: 2026-06-02 09:31:43.564915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f3a5ee5cd3'
down_revision: Union[str, Sequence[str], None] = '47458769c1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department', schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(length=200), autoincrement=False, nullable=True), schema='users_shema')
    # ### end Alembic commands ###
