"""002 add new column role in table Messages

Revision ID: 2c1c4cc00f90
Revises: 8506a89ad7d9
Create Date: 2026-06-18 14:43:15.151190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c1c4cc00f90'
down_revision: Union[str, Sequence[str], None] = '8506a89ad7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('USER', 'ASSISTANT', name='userrole', schema='users_shema')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('messages', sa.Column('role',user_role_enum , nullable=True), schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'role', schema='users_shema')
    # ### end Alembic commands ###
    user_role_enum = sa.Enum('USER', 'ASSISTANT', name='userrole', schema='users_shema')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
