"""Update type column message.id in uuid7

Revision ID: 3cc4eeff043e
Revises: a334979b1ac4
Create Date: 2026-05-22 13:15:57.514000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc4eeff043e'
down_revision: Union[str, Sequence[str], None] = 'a334979b1ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary_link', sa.UUID(), nullable=True), schema='users_shema')
    op.add_column('chats', sa.Column('summary_count', sa.Integer(), nullable=True), schema='users_shema')
    op.execute("ALTER TABLE users_shema.messages ALTER COLUMN id DROP DEFAULT")
    op.alter_column('messages', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               schema='users_shema',
               postgresql_using='gen_random_uuid()')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='users_shema')
    op.drop_column('chats', 'summary_count', schema='users_shema')
    op.drop_column('chats', 'summary_link', schema='users_shema')
    # ### end Alembic commands ###
