"""new column in table users and new table deportament

Revision ID: 47458769c1af
Revises: 89893c595de4
Create Date: 2026-06-01 15:45:03.429609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47458769c1af'
down_revision: Union[str, Sequence[str], None] = '89893c595de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users_shema.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users_shema'
    )
    op.add_column('users', sa.Column('department', sa.String(length=200), nullable=True), schema='users_shema')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False), schema='users_shema')
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=True), schema='users_shema')
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True), schema='users_shema')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], source_schema='users_shema', referent_schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='users_shema', type_='foreignkey')
    op.drop_column('users', 'department_id', schema='users_shema')
    op.drop_column('users', 'email', schema='users_shema')
    op.drop_column('users', 'is_active', schema='users_shema')
    op.drop_column('users', 'department', schema='users_shema')
    op.drop_table('departments', schema='users_shema')
    # ### end Alembic commands ###
