"""001: first migration when switching to a web socket

Revision ID: 8506a89ad7d9
Revises: 
Create Date: 2026-06-16 09:44:37.873987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8506a89ad7d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS users_shema")
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users_shema.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users_shema'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['users_shema.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    sa.UniqueConstraint('login'),
    schema='users_shema'
    )
    op.create_index('idx_user_on_email_login', 'users', ['email', 'login'], unique=False, schema='users_shema')
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('chat_type', sa.Enum('DIRECT', 'GROUP', 'AI_DIRECT', name='chattype', schema='users_shema', inherit_schema=True), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('summary_link', sa.Integer(), nullable=True),
    sa.Column('summary_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users_shema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='users_shema'
    )
    op.create_index('idx_chat_on_guid', 'chats', ['guid'], unique=False, schema='users_shema')
    op.create_index('idx_chat_on_type', 'chats', ['chat_type'], unique=False, schema='users_shema')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_shema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='users_shema'
    )
    op.create_table('chat_participant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['users_shema.chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    schema='users_shema'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'FILE', name='messagetype', schema='users_shema', inherit_schema=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['users_shema.chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shema.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid'),
    schema='users_shema'
    )
    op.create_index('idx_message_on_chat_id', 'messages', ['chat_id'], unique=False, schema='users_shema')
    op.create_index('idx_message_on_chat_user', 'messages', ['chat_id', 'user_id'], unique=False, schema='users_shema')
    op.create_index('idx_message_on_user_id', 'messages', ['user_id'], unique=False, schema='users_shema')
    op.create_table('read_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['users_shema.chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users_shema.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_read_status_user_chat'),
    schema='users_shema'
    )
    op.create_index('idx_read_status_on_chat_id', 'read_status', ['chat_id'], unique=False, schema='users_shema')
    op.create_index('idx_read_status_on_user_id', 'read_status', ['user_id'], unique=False, schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_read_status_on_user_id', table_name='read_status', schema='users_shema')
    op.drop_index('idx_read_status_on_chat_id', table_name='read_status', schema='users_shema')
    op.drop_table('read_status', schema='users_shema')
    op.drop_index('idx_message_on_user_id', table_name='messages', schema='users_shema')
    op.drop_index('idx_message_on_chat_user', table_name='messages', schema='users_shema')
    op.drop_index('idx_message_on_chat_id', table_name='messages', schema='users_shema')
    op.drop_table('messages', schema='users_shema')
    op.drop_table('chat_participant', schema='users_shema')
    op.drop_table('refresh_tokens', schema='users_shema')
    op.drop_index('idx_chat_on_type', table_name='chats', schema='users_shema')
    op.drop_index('idx_chat_on_guid', table_name='chats', schema='users_shema')
    op.drop_table('chats', schema='users_shema')
    op.drop_index('idx_user_on_email_login', table_name='users', schema='users_shema')
    op.drop_table('users', schema='users_shema')
    op.drop_table('departments', schema='users_shema')
    op.execute("DROP SCHEMA IF EXISTS users_shema CASCADE")
    # ### end Alembic commands ###
