"""add index in table message on column (chat_id,id)

Revision ID: 89893c595de4
Revises: 3cc4eeff043e
Create Date: 2026-05-25 15:35:47.541599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89893c595de4'
down_revision: Union[str, Sequence[str], None] = '3cc4eeff043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_chat_id_id', 'messages', ['chat_id', 'id'], unique=False, schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_chat_id_id', table_name='messages', schema='users_shema')
    # ### end Alembic commands ###
