"""update type column users.messages.source on JSONB

Revision ID: 8c4909540cff
Revises: ee42205a5ded
Create Date: 2026-04-17 11:11:43.796548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c4909540cff'
down_revision: Union[str, Sequence[str], None] = 'ee42205a5ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='users_shema')
    op.drop_column('messages', 'source', schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True), schema='users_shema')
    op.drop_column('messages', 'sources', schema='users_shema')
    # ### end Alembic commands ###
