"""update: new column Chats.summary

Revision ID: cfa22d023e6d
Revises: 8c4909540cff
Create Date: 2026-05-07 13:30:47.593196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa22d023e6d'
down_revision: Union[str, Sequence[str], None] = '8c4909540cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('summary', sa.Text(), nullable=True), schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'summary', schema='users_shema')
    # ### end Alembic commands ###
