"""new colomn for source answer llm

Revision ID: ee42205a5ded
Revises: 492eefd1f569
Create Date: 2026-04-17 10:33:50.709332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee42205a5ded'
down_revision: Union[str, Sequence[str], None] = '492eefd1f569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_user_flags', schema='users_shema')
    op.add_column('messages', sa.Column('source', sa.Text(), nullable=True), schema='users_shema')
    op.add_column('messages', sa.Column('context', sa.Text(), nullable=True), schema='users_shema')
    op.add_column('messages', sa.Column('total', sa.Integer(), nullable=True), schema='users_shema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'total', schema='users_shema')
    op.drop_column('messages', 'context', schema='users_shema')
    op.drop_column('messages', 'source', schema='users_shema')
    op.create_table('admin_user_flags',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_shema.users.id'], name=op.f('admin_user_flags_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('admin_user_flags_pkey')),
    schema='users_shema'
    )
    # ### end Alembic commands ###
