# Шаг 1: Выбираем базовый образ
FROM python:3.12

# Шаг 2: Создаём рабочую директорию
WORKDIR /app

# Шаг 3: Копируем файл с зависимостями
COPY requirements.txt ./

# Шаг 4: Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Шаг 5: Копируем весь проект в контейнер
COPY . .

# Шаг 6: Указываем команду для запуска приложения
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]dock