[tool.poetry]
name = "rag-programm"
version = "0.1.0"
description = "RAG Chat Application"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "app" },
    { include = "main.py" }
]

[tool.poetry.dependencies]
python = ">=3.12,<4.0.0"
fastapi = ">=0.110.0,<0.111.0"
uvicorn = ">=0.29.0,<0.30.0"
sqlalchemy = ">=2.0.0,<3.0.0"
python-dotenv = ">=1.0.0,<2.0.0"
pyjwt = ">=2.8.0,<3.0.0"
pwdlib = {extras = ["argon2"], version = "^0.3.0"}
pydantic = ">=2.5.0,<3.0.0"
qdrant-client = ">=1.9.0,<2.0.0"
sentence-transformers = ">=2.7.0,<3.0.0"
numpy = ">=1.24.0,<2.0.0"
langchain-core = ">=0.1.0,<0.2.0"
langchain-community = ">=0.0.0,<0.1.0"
langchain-google-genai = ">=0.0.0,<0.1.0"
langchain-huggingface = ">=0.0.0,<0.1.0"
uuid6 = ">=2024.0.0,<2025.0.0"
pypdf2 = "^3.0.1"
pdfminer-six = "^20251107"
pdfplumber = "^0.11.8"
pdf2image = "^1.17.0"
pytesseract = "^0.3.13"
pypdf = "^6.4.0"
tabulate = "^0.9.0"
pymupdf = "^1.26.6"
unstructured = "^0.18.21"
pi-heif = "^1.1.1"
matplotlib = "^3.10.7"

[tool.poetry.group.dev.dependencies]
alembic = ">=1.13.0,<2.0.0"
pytest = ">=7.0.0,<8.0.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
