"""update users table:colomn chat_id type str->uuid7

Revision ID: bc73427871e2
Revises: de11312f6b7f
Create Date: 2025-11-25 08:52:59.548929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc73427871e2'
down_revision: Union[str, Sequence[str], None] = 'de11312f6b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
