version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/pgdata
      # Дополнительные настройки для SQLAlchemy
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # UTF-8 по умолчанию
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myapp_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
