export const BASE_API_URL = import.meta.env.VITE_API_URL || "";

export const ENDPOINTS = {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    REFRESH: "/auth/refresh",
    LOGOUT: "/auth/logout",
    PROFILE: "/api/profile",
    CONVERSATIONS: "/api/chats",
    MESSAGES: (chatId) => `/api/chats/${chatId}/messages`,
    MESSAGES_STREAM: (chatId) => `/api/chats/${chatId}/messages/stream`,
    CHAT_SOURCE_CHUNK: (parentId) => `/api/chats/sources/${parentId}`,
    USERS_SEARCH: (q) => `/api/users/search?q=${encodeURIComponent(q)}`,
    MESSENGER_CHATS: "/messenger/chats/",
    MESSENGER_DIRECT: "/messenger/chats/direct",
    MESSENGER_CHAT: (guid) => `/messenger/chats/${guid}`,
    MESSENGER_MESSAGES: (guid) => `/messenger/chats/${guid}/messages`,
    MESSENGER_WS: (token) => {
        const proto = window.location.protocol === 'https:' ? 'wss' : 'ws';
        return `${proto}://${window.location.host}/websocket/ws/?token=${token}`;
    },
    KNOWLEDGE_DOCUMENTS: "/api/knowledge/documents",
    KNOWLEDGE_DOCUMENT_STATUS: (id) => `/api/knowledge/documents/${id}`,
    KNOWLEDGE_DOCUMENT_CHAPTER: (id, idx) => `/api/knowledge/documents/${id}/chapters/${idx}`,
    PROJECTS: "/api/projects",
    NOTES: "/api/notes",
    NOTE: (guid) => `/api/notes/${guid}`,
    NOTE_GENERATE: (guid) => `/api/notes/${guid}/generate`,
    NOTE_INDEX: (guid) => `/api/notes/${guid}/index`,
    ADMIN_HEALTH: "/admin/system/health",
    ADMIN_DOCUMENTS: "/admin/documents",
    ADMIN_DOCUMENT_UPLOAD_LINK: "/admin/documents/upload-link",
    ADMIN_DOCUMENT_REINDEX: (id) => `/admin/documents/${id}/reindex`,
    ADMIN_DOCUMENT_SUMMARIZE: (id) => `/admin/documents/${id}/summarize`,
    ADMIN_DOCUMENTS_BULK_REINDEX: "/admin/documents/bulk-reindex",
    ADMIN_DOCUMENTS_BULK_SUMMARIZE: "/admin/documents/bulk-summarize",
    ADMIN_DOCUMENT_DELETE: (id) => `/admin/documents/${id}`,
    ADMIN_USERS: "/admin/users/repo",
    ADMIN_USER_ROLE: (id) => `/admin/users/repo/${id}/role`,
    ADMIN_TASKS: "/admin/tasks",
    ADMIN_TASK_REVOKE: (id) => `/admin/tasks/${id}/revoke`,
};