from rag_service.domain.errors.base import (
    AppError,
    DuplicateFilenameError,
    InvalidDocumentIdError,
    UploadValidationError,
    WebhookAuthorizationError,
)
from rag_service.domain.errors.postgres import (
    ChunkInsertError,
    DeadlockRetryExceeded,
    DocumentAlreadyExists,
    DocumentByStorageKeyNotFound,
    DocumentCreateError,
    DocumentDeleteError,
    DocumentNotFound,
    DocumentReadError,
    DocumentRepositoryError,
    DocumentUpdateError,
    PostgresError,
)
from rag_service.domain.errors.storage import (
    StorageDeleteError,
    StorageError,
    StorageMetadataError,
    StorageReadError,
    StorageWriteError,
)
from rag_service.domain.errors.vector import (
    VectorCollectionError,
    VectorDeleteError,
    VectorSearchError,
    VectorStoreError,
    VectorUpsertError,
)

__all__ = [
    "AppError",
    "DuplicateFilenameError",
    "UploadValidationError",
    "WebhookAuthorizationError",
    "InvalidDocumentIdError",
    "PostgresError",
    "DocumentAlreadyExists",
    "DocumentByStorageKeyNotFound",
    "DocumentNotFound",
    "DocumentRepositoryError",
    "DocumentReadError",
    "DocumentCreateError",
    "DocumentUpdateError",
    "DocumentDeleteError",
    "ChunkInsertError",
    "DeadlockRetryExceeded",
    "StorageError",
    "StorageReadError",
    "StorageWriteError",
    "StorageDeleteError",
    "StorageMetadataError",
    "VectorStoreError",
    "VectorUpsertError",
    "VectorSearchError",
    "VectorDeleteError",
    "VectorCollectionError",
]
