"""rag_kernal_schema

Revision ID: 0904163c21ed
Revises: 
Create Date: 2026-02-17 08:59:37.322535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0904163c21ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS "rag_kernel"')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'error', name='document_status_enum', schema='rag_kernel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_documents_file_hash'),
    schema='rag_kernel'
    )
    op.create_index('ix_documents_file_hash', 'documents', ['file_hash'], unique=False, schema='rag_kernel')
    op.create_table('parent_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_kernel.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uq_parent_chunks_doc_chunk_index'),
    schema='rag_kernel'
    )
    op.create_index('ix_parent_chunks_chunk_index', 'parent_chunks', ['chunk_index'], unique=False, schema='rag_kernel')
    op.create_index('ix_parent_chunks_doc_id', 'parent_chunks', ['doc_id'], unique=False, schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parent_chunks_doc_id', table_name='parent_chunks', schema='rag_kernel')
    op.drop_index('ix_parent_chunks_chunk_index', table_name='parent_chunks', schema='rag_kernel')
    op.drop_table('parent_chunks', schema='rag_kernel')
    op.drop_index('ix_documents_file_hash', table_name='documents', schema='rag_kernel')
    op.drop_table('documents', schema='rag_kernel')
    # ### end Alembic commands ###
