"""documents: new column file_size

Revision ID: 329d811f2b9d
Revises: de06bc2f3c1d
Create Date: 2026-05-05 16:45:52.823044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329d811f2b9d'
down_revision: Union[str, Sequence[str], None] = 'de06bc2f3c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True), schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_size', schema='rag_kernel')
    # ### end Alembic commands ###
