"""First migration in posgres:18

Revision ID: 79e89f76e01d
Revises: 
Create Date: 2026-05-22 11:14:10.797643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79e89f76e01d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS rag_kernel")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('s3key', sa.String(length=1024), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'uploading', 'processing', 'extracting', 'indexing', 'completed', 'error','duplicate')", name='ck_documents_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', name='uq_documents_file_hash'),
    schema='rag_kernel'
    )
    op.create_index('ix_documents_file_hash', 'documents', ['file_hash'], unique=False, schema='rag_kernel')
    op.create_table('parent_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_num', sa.String(length=32), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_kernel.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', name='uq_parent_chunks_doc_chunk_index'),
    schema='rag_kernel'
    )
    op.create_index('ix_parent_chunks_chunk_index', 'parent_chunks', ['chunk_index'], unique=False, schema='rag_kernel')
    op.create_index('ix_parent_chunks_doc_id', 'parent_chunks', ['doc_id'], unique=False, schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parent_chunks_doc_id', table_name='parent_chunks', schema='rag_kernel')
    op.drop_index('ix_parent_chunks_chunk_index', table_name='parent_chunks', schema='rag_kernel')
    op.drop_table('parent_chunks', schema='rag_kernel')
    op.drop_index('ix_documents_file_hash', table_name='documents', schema='rag_kernel')
    op.drop_table('documents', schema='rag_kernel')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS rag_kernel")
