"""add document_chapters and document_tables

Revision ID: 87b0b83e6cf1
Revises: 79e89f76e01d
Create Date: 2026-07-08 13:43:01.863592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b0b83e6cf1'
down_revision: Union[str, Sequence[str], None] = '79e89f76e01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('chapter_number', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('s3_md_path', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_kernel.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'chapter_number', name='uq_document_chapters_doc_chapter_number'),
    schema='rag_kernel'
    )
    op.create_index('ix_document_chapters_doc_id', 'document_chapters', ['doc_id'], unique=False, schema='rag_kernel')
    op.create_table('document_tables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('s3_csv_path', sa.String(length=1024), nullable=False),
    sa.Column('s3_html_path', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['rag_kernel.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'table_index', name='uq_document_tables_doc_table_index'),
    schema='rag_kernel'
    )
    op.create_index('ix_document_tables_doc_id', 'document_tables', ['doc_id'], unique=False, schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_tables_doc_id', table_name='document_tables', schema='rag_kernel')
    op.drop_table('document_tables', schema='rag_kernel')
    op.drop_index('ix_document_chapters_doc_id', table_name='document_chapters', schema='rag_kernel')
    op.drop_table('document_chapters', schema='rag_kernel')
    # ### end Alembic commands ###
