"""column file_hash nullable

Revision ID: c936e7b091b7
Revises: c1f4e2b9d8aa
Create Date: 2026-04-29 08:29:23.317874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c936e7b091b7'
down_revision: Union[str, Sequence[str], None] = 'c1f4e2b9d8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               schema='rag_kernel')
    # ### end Alembic commands ###
