"""documents: updated_at, rename s3key to s3key

Revision ID: de06bc2f3c1d
Revises: dd62bdefa386
Create Date: 2026-05-05 15:28:55.690147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de06bc2f3c1d'
down_revision: Union[str, Sequence[str], None] = 'dd62bdefa386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='rag_kernel')
    op.add_column('documents', sa.Column('s3key', sa.String(length=1024), nullable=True), schema='rag_kernel')
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               schema='rag_kernel')
    op.drop_column('documents', 's3key', schema='rag_kernel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True), schema='rag_kernel')
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='rag_kernel')
    op.drop_column('documents', 's3key', schema='rag_kernel')
    op.drop_column('documents', 'updated_at', schema='rag_kernel')
    # ### end Alembic commands ###
